# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f10aebd54a84cb19581c37d7aac8a56e765787783062f1a65d23265b6810347bcb7522cbda24b00117615ac4ae772cf608d7d638dcae35e2d90dad267344134

test:
  secret_key_base: b0e75032162656f4a9645e232ecb1846490400510996705e3d82058ef3fb9f031775df96c3f6c3119ccaebfab4023d8324b0972e1189ba85e875608c507302d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
